---
- name: install requirements
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - wget
  - curl
  - less
  - vim
  - git
  - build-essential
  - xmlto
#  libxslt requires these 3
  - libxml2-dev
  - libxslt1-dev
  - python-dev
  - openssl
  - libssl-dev
  - libncurses5-dev
  - automake
  - autoconf

- name: install rebar
  get_url:
    url: https://github.com/rebar/rebar/wiki/rebar
    dest: /bin/rebar
    mode: 0777

- name: install kerl
  get_url:
    url: https://raw.githubusercontent.com/kerl/kerl/master/kerl
    dest: /kerl
    mode: 0777

- name: build Erlang {{ otp_version }}
  command: /kerl build {{ otp_version }} {{ otp_version }}
  environment:
      KERL_CONFIGURE_OPTIONS: '--with-ssl=/usr/include/openssl --without-javac --enable-shared-zlib --enable-dynamic-ssl-lib --enable-hipe --enable-smp-support --enable-threads --enable-kernel-poll'

- name: install Erlang {{ otp_version }}
  command: /kerl install {{ otp_version }} /opt/kerl/{{ otp_version }}

- name: configure Erlang activation for bash (for container)
  lineinfile:
      insertafter: EOF
      path: /etc/bash.bashrc
      line: 'source /opt/kerl/{{ otp_version }}/activate'

- name: 'download elixir {{ elixir_version }}'
  get_url:
    url: https://github.com/elixir-lang/elixir/archive/v{{ elixir_version }}.tar.gz
    dest: /elixir-v{{ elixir_version }}.tar.gz

- name: unzip elixir in /opt
  unarchive:
      src: /elixir-v{{ elixir_version }}.tar.gz
      dest: /opt
      remote_src: yes

- name: install Elixir builder script
  template: src=build-elixir.sh dest={{ elixir_path }} mode=0700

- name: build Elixir
  command: '{{ elixir_path }}/build-elixir.sh'

- name: add elixir's bin to PATH (for container)
  lineinfile:
      insertafter: EOF
      path: /etc/bash.bashrc
      line: 'export PATH=$PATH:{{ elixir_path }}/bin'

- name: clone RabbitMQ server source
  git:
      repo: https://github.com/rabbitmq/rabbitmq-server.git
      dest: '{{ rabbitmq_destination }}'
      version: master

- name: install RabbitMQ builder script
  template: src=build-rabbitmq.sh dest={{ rabbitmq_destination }} mode=0700

- name: build RabbitMQ server
  command: '{{ rabbitmq_destination }}/build-rabbitmq.sh'
